version: '2'
services:
  etldataloadservice-app:
    image: etldataloadservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://etldataloadservice-postgresql:5432/etldataloadservice
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  etldataloadservice-postgresql:
    extends:
      file: postgresql.yml
      service: etldataloadservice-postgresql
